server:
  port: 8084
# DataSource Config
spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    #2.?? return ????
    publisher-returns: true
    #3.????Mandatory,????????,????????????????????
    template:
      mandatory: true



